Fix rocskdb 2
These changes will need to be sorted out someday

diff --git a/build_tools/build_detect_platform b/build_tools/build_detect_platform
--- a/build_tools/build_detect_platform
+++ b/build_tools/build_detect_platform
@@ -500,34 +500,36 @@ EOF
         fi
     fi
 
-    if ! test $ROCKSDB_DISABLE_BACKTRACE; then
-        # Test whether backtrace is available
-        $CXX $PLATFORM_CXXFLAGS -x c++ - -o /dev/null 2>/dev/null  <<EOF
-          #include <execinfo.h>
-          int main() {
-            void* frames[1];
-            backtrace_symbols(frames, backtrace(frames, 1));
-            return 0;
-          }
-EOF
-        if [ "$?" = 0 ]; then
-            COMMON_FLAGS="$COMMON_FLAGS -DROCKSDB_BACKTRACE"
-        else
-            # Test whether execinfo library is installed
-            $CXX $PLATFORM_CXXFLAGS -lexecinfo -x c++ - -o /dev/null 2>/dev/null  <<EOF
-              #include <execinfo.h>
-              int main() {
-                void* frames[1];
-                backtrace_symbols(frames, backtrace(frames, 1));
-              }
-EOF
-            if [ "$?" = 0 ]; then
-                COMMON_FLAGS="$COMMON_FLAGS -DROCKSDB_BACKTRACE"
-                PLATFORM_LDFLAGS="$PLATFORM_LDFLAGS -lexecinfo"
-                JAVA_LDFLAGS="$JAVA_LDFLAGS -lexecinfo"
-            fi
-        fi
-    fi
+# Fails to detect that execinfo isn't available. Commenting out for now
+#
+#     if ! test $ROCKSDB_DISABLE_BACKTRACE; then
+#         # Test whether backtrace is available
+#         $CXX $PLATFORM_CXXFLAGS -x c++ - -o /dev/null 2>/dev/null  <<EOF
+#           #include <execinfo.h>
+#           int main() {
+#             void* frames[1];
+#             backtrace_symbols(frames, backtrace(frames, 1));
+#             return 0;
+#           }
+# EOF
+#         if [ "$?" = 0 ]; then
+#             COMMON_FLAGS="$COMMON_FLAGS -DROCKSDB_BACKTRACE"
+#         else
+#             # Test whether execinfo library is installed
+#             $CXX $PLATFORM_CXXFLAGS -lexecinfo -x c++ - -o /dev/null 2>/dev/null  <<EOF
+#               #include <execinfo.h>
+#               int main() {
+#                 void* frames[1];
+#                 backtrace_symbols(frames, backtrace(frames, 1));
+#               }
+# EOF
+#             if [ "$?" = 0 ]; then
+#                 COMMON_FLAGS="$COMMON_FLAGS -DROCKSDB_BACKTRACE"
+#                 PLATFORM_LDFLAGS="$PLATFORM_LDFLAGS -lexecinfo"
+#                 JAVA_LDFLAGS="$JAVA_LDFLAGS -lexecinfo"
+#             fi
+#         fi
+#     fi
 
     if ! test $ROCKSDB_DISABLE_PG; then
         # Test if -pg is supported
