Fix rocksdb

diff --git a/build_tools/build_detect_platform b/build_tools/build_detect_platform
--- a/build_tools/build_detect_platform
+++ b/build_tools/build_detect_platform
@@ -723,19 +723,21 @@ if test "$TRY_SSE_ETC"; then
   TRY_LZCNT="-mlzcnt"
 fi
 
-$CXX $PLATFORM_CXXFLAGS $COMMON_FLAGS $TRY_SSE42 -x c++ - -o /dev/null 2>/dev/null <<EOF
-  #include <cstdint>
-  #include <nmmintrin.h>
-  int main() {
-    volatile uint32_t x = _mm_crc32_u32(0, 0);
-    (void)x;
-  }
-EOF
-if [ "$?" = 0 ]; then
-  COMMON_FLAGS="$COMMON_FLAGS $TRY_SSE42 -DHAVE_SSE42"
-elif test "$USE_SSE"; then
-  echo "warning: USE_SSE specified but compiler could not use SSE intrinsics, disabling" >&2
-fi
+# This script fails to detect that <nmmintrin.h> isn't available. I don't know why, I'm just commenting this out for now.
+#
+# $CXX $PLATFORM_CXXFLAGS $COMMON_FLAGS $TRY_SSE42 -x c++ - -o /dev/null 2>/dev/null <<EOF
+#   #include <cstdint>
+#   #include <nmmintrin.h>
+#   int main() {
+#     volatile uint32_t x = _mm_crc32_u32(0, 0);
+#     (void)x;
+#   }
+# EOF
+# if [ "$?" = 0 ]; then
+#   COMMON_FLAGS="$COMMON_FLAGS $TRY_SSE42 -DHAVE_SSE42"
+# elif test "$USE_SSE"; then
+#   echo "warning: USE_SSE specified but compiler could not use SSE intrinsics, disabling" >&2
+# fi
 
 $CXX $PLATFORM_CXXFLAGS $COMMON_FLAGS $TRY_PCLMUL -x c++ - -o /dev/null 2>/dev/null <<EOF
   #include <cstdint>
@@ -754,20 +756,22 @@ elif test "$USE_SSE"; then
   echo "warning: USE_SSE specified but compiler could not use PCLMUL intrinsics, disabling" >&2
 fi
 
-$CXX $PLATFORM_CXXFLAGS $COMMON_FLAGS $TRY_AVX2 -x c++ - -o /dev/null 2>/dev/null <<EOF
-  #include <cstdint>
-  #include <immintrin.h>
-  int main() {
-    const auto a = _mm256_setr_epi32(0, 1, 2, 3, 4, 7, 6, 5);
-    const auto b = _mm256_permutevar8x32_epi32(a, a);
-    (void)b;
-  }
-EOF
-if [ "$?" = 0 ]; then
-  COMMON_FLAGS="$COMMON_FLAGS $TRY_AVX2 -DHAVE_AVX2"
-elif test "$USE_SSE"; then
-  echo "warning: USE_SSE specified but compiler could not use AVX2 intrinsics, disabling" >&2
-fi
+# This script fails to detect that <immintrin.h> isn't available. I don't know why, I'm just commenting this out for now.
+#
+# $CXX $PLATFORM_CXXFLAGS $COMMON_FLAGS $TRY_AVX2 -x c++ - -o /dev/null 2>/dev/null <<EOF
+#   #include <cstdint>
+#   #include <immintrin.h>
+#   int main() {
+#     const auto a = _mm256_setr_epi32(0, 1, 2, 3, 4, 7, 6, 5);
+#     const auto b = _mm256_permutevar8x32_epi32(a, a);
+#     (void)b;
+#   }
+# EOF
+# if [ "$?" = 0 ]; then
+#   COMMON_FLAGS="$COMMON_FLAGS $TRY_AVX2 -DHAVE_AVX2"
+# elif test "$USE_SSE"; then
+#   echo "warning: USE_SSE specified but compiler could not use AVX2 intrinsics, disabling" >&2
+# fi
 
 $CXX $PLATFORM_CXXFLAGS $COMMON_FLAGS $TRY_BMI -x c++ - -o /dev/null 2>/dev/null <<EOF
   #include <cstdint>
